def menu ():
    print("Bienvenido a la Calculadora!")
    print("")
    print("1. Suma")
    print("2. Resta")
    print("3. Multipicación")
    print("4. División")
    print("5. Media")
    print("6. Factorial")
    print("7. Primo")
    print("8. División entera")
